
#type: args

train:
  epochs: 200
  batch_size: 256 
  lr: 0.0005

diffusion:
  layers: 6 
  channels: 128 
  nheads: 8
  diffusion_embedding_dim: 512
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 20
  schedule: "quad"

model:
  is_unconditional: 0
  timeemb: 256
  featureemb: 64
  target_strategy: "test"
